config/routes.rb
Rails.application.routes.draw do
  # device
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show]
  root 'pages#home'
  get '/howto', to: 'pages#howto'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :clans do
    resources :requests, only: %i(create destroy)
    resources :belongings, only: %i(create destroy)
    resources :boards, only: [:index, :create, :update, :destroy]
  end
end

app/models/clan.rb
class Clan < ApplicationRecord
  acts_as_taggable
  enum status: { メンバー募集中: 0, 非募集: 1, 活動休止中: 2 }
  enum atomosphere: { エンジョイ: 0, エンジョイandガチ: 1, ガチ: 2 }
  enum average_age: { １０代: 0, ２０代: 1, ３０代: 2, ４０代: 3, ５０代以上: 4 }
  mount_uploader :image, ImageUploader
  has_many :belongings, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :users, through: :belongings
  has_many :boards, dependent: :destroy
  validates :name, presence: true, length: { maximum: 10 }
  validates :tag_list, presence: true
  validates :level, length: { maximum: 10 }
  validates :clan_introduction, length: { maximum: 400 }
  # ユーザがコミュニティに所属していればtrueを返す
  def user_belonging?(user)
    users.include?(user)
  end
end

app/controllers/clans_controller.rb
class ClansController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Clan.ransack(params[:q])
    @tags = ActsAsTaggableOn::Tag.all
    if params[:tag_name]
      @clans = @q.result(distinct: true).tagged_with("#{params[:tag_name]}").
        page(params[:page]).per(12)
    else
      @clans = @q.result(distinct: true).page(params[:page]).per(8)
    end
  end

  def show
    @clan = Clan.find(params[:id])
    @requests = Request.where(clan_id: params[:clan_id])
    @belongings = Belonging.where(clan_id: @clan.id)
    @board = Board.new
    @boards = @clan.boards
    if current_user
      @belonging = Belonging.find_by(clan_id: @clan.id, user_id: current_user.id)
      @request = Request.find_by(clan_id: @clan.id, user_id: current_user.id)
    end
  end

  def new
    @clan = Clan.new
    @clan.users << current_user
    @tags = ActsAsTaggableOn::Tag.all
  end

  def create
    @clan = Clan.new(clan_params)
    @tags = ActsAsTaggableOn::Tag.all
    if @clan.save
      Belonging.create!(clan_id: @clan.id, user_id: current_user.id, admin_flg: '1')
      redirect_to root_path, notice: 'クランを作成しました'
    else
      render :new
    end
  end

  def edit
    @clan = Clan.find(params[:id])
    @tags = ActsAsTaggableOn::Tag.all
  end

  def update
    @clan = Clan.find(params[:id])
    @tags = ActsAsTaggableOn::Tag.all
    if @clan.update(clan_params)
      redirect_to clan_path(@clan), notice: 'クランプロフィールを編集しました'
    else
      render :edit
    end
  end

  def destroy
    @clan = Clan.find(params[:id])
    @clan.destroy
    redirect_to clans_url, notice: "クラン「#{@clan.name}」を削除しました。"
  end

  private

  def clan_params
    params.require(:clan).permit(
      :name, :image, :level, :status, :atomosphere,
      :average_age, :clan_introduction, :tag_list, user_ids: []
    )
  end
end

app/views/clans/edit.html.erb
<%= render partial:'layouts/error', locals:{object: @clan} %>
<div class="container">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 offset-sm-2">
      <div class="guide-content">
        <div class="page_title text-center">
            <h5 style="font-size: x-large; font-weight: bold;">クラン編集</h5>
        </div>
      </div>
      <%= form_with(model: @clan, local: true) do |f| %>
        <div class="post-image-prev text-center">
          <% if @clan.image? %>
            <%= image_tag "#{@clan.image}", alt: "post-image", id: "img_prev", class: "clan_image" %>
          <% else %>
            <%= image_tag "default_clan.png", alt: "post-image", id: :img_prev, class: "clan_image" %>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.file_field :image, accept: 'image/jpeg, image/gif, image/png', id: "image-select-btn" %>
        </div>
        <div class="form-group">
          <span class="badge badge-danger">必須</span><%= f.label :【名前】 %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :【レベル】 %>
          <%= f.text_field :level, autofocus: true, autocomplete: "level", class: "form-control" %>
        </div>
        <div class=":status-field">
            <%= f.label :【ステータス】 %><br />
            <%= f.select :status, [["メンバー募集中", "メンバー募集中"], ["非募集", "非募集"], ["活動休止中", "活動休止中"]], include_blank: "選択してください" %>
        </div>
        <div class=":atomosphere-field">
            <%= f.label :【雰囲気】 %><br />
            <%= f.select :atomosphere, [["エンジョイ", "エンジョイ"], ["エンジョイandガチ", "エンジョイandガチ"], ["ガチ", "ガチ"]], include_blank: "選択してください" %>
        </div>
        <div class="age-field">
            <%= f.label :【平均年齢】 %><br />
            <%= f.select :average_age, [["１０代", "１０代"], ["２０代", "２０代"], ["３０代", "３０代"], ["４０代", "４０代"], ["５０代以上", "５０代以上"]], include_blank: "選択してください" %>
        </div>
        <div class="tag_list-field">
          <span class="badge badge-danger">必須</span><%= f.label :【ゲーム】 %><br />
          <%= f.collection_select:tag_list, @tags.all, :name, :name, include_blank: "選択してください" %>
        </div>
        <div class="form-group">
          <%= f.label :【クラン紹介】 %>(400文字以内)
          <%= f.text_area :clan_introduction, :rows => "7", autofocus: true, autocomplete: "clan_introduction", class: "form-control" %>
        </div>
        <div class="actions">
          <p><%= f.submit "変更する", class: "btn btn3 col-sm-12" %></p>
        </div>
      <% end %>
      <p><%= link_to 'クランへ戻る', "#", class: "btn btn4 col-sm-12" %></p>
      <p><%= link_to "クランを削除する", clan_path, data: { confirm: "本当にクランを削除しますか?" }, method: :delete, class: "btn btn_red col-sm-12" %></p>
    </div>
  </div>
</div>

app/views/clans/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-sm-0 col-sm-12 offset-sm-0">
      <div class="guide-content">
        <div class="page_title text-center">
          <h5 style="font-size: x-large; font-weight: bold;">クラン一覧</h5>
        </div>
      </div>
      <dl class="searchbox">
        <%= search_form_for @q do |f| %>
          <dt><%= f.search_field :name_cont, placeholder: "クラン名を入力", class: "form-control" %></dt>
          <dd><button type="submit" class="search-btn"><i class="fas fa-search" style="color: grey;"></i></button></dd>
        <% end %>
      </dl>
      <% @tags.each do |tag| %>
          <%= link_to "#{tag.name}(#{tag.taggings_count})", clans_path(tag_name: tag.name), class: "badge badge-primary"%>
      <% end %>
      <ul class="clans">
        <% @clans.each do |clan| %>
          <li>
            <div class="profile-card">
              <%= link_to(clan, data: {"turbolinks" => false} ) do %>
              <div class="profile-card__inner">
                <div class="profile-thumb">
                  <% if clan.image? %>
                    <img src=<%= clan.image %>>
                  <% else %>
                    <%= image_tag 'default_clan.png' %>
                  <% end %>
                </div>
                <div class="profile-content text-center">
                  <span class="profile-name"><%= clan.name %>(<%= clan.users.count %>)</span>
                  <%= raw(clan.tag_list.map { |t| link_to t, clans_path(tag_name: t), class: "profile-job" }.join(' ')) %>
                  <span class="profile-intro">
                    <table>
                      <tr><th>ステータス</th><td><%= clan.status %></td></tr>
                      <tr><th>レベル</th><td><%= clan.level %></td></tr>
                      <tr><th>雰囲気</th><td><%= clan.atomosphere %></td></tr>
                      <tr><th>平均年齢</th><td><%= clan.average_age %></td></tr>
                    </table>
                  </span>
                </div>
              </div>
            <% end %>
            </div>
          </li>
        <% end %>
      </ul>
      <%= paginate @clans %>
    </div>
  </div>
</div>

app/views/clans/new.html.erb
<%= render partial:'layouts/error', locals:{object: @clan} %>
<div class="container">
  <div class="row">
    <div class="offset-sm-2 col-sm-8 offset-sm-2">
      <div class="guide-content">
        <div class="page_title text-center">
            <h5 style="font-size: x-large; font-weight: bold;">クラン新規登録</h5>
        </div>
      </div>
      <h6 style="color: grey;">登録情報はクランアイコン・クラン紹介も含めていつでも変更できます。</h6>
      <%= form_with(model: @clan, local: true) do |f| %>
        <div class="form-group">
          <span class="badge badge-danger">必須</span><%= f.label :【名前】 %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :【レベル】 %>
          <%= f.text_field :level, autofocus: true, autocomplete: "level", class: "form-control" %>
        </div>
        <div class=":status-field">
            <%= f.label :【ステータス】 %><br />
            <%= f.select :status, [["メンバー募集中", "メンバー募集中"], ["非募集", "非募集"], ["活動休止中", "活動休止中"]], include_blank: "選択してください" %>
        </div>
        <div class=":atomosphere-field">
            <%= f.label :【雰囲気】 %><br />
            <%= f.select :atomosphere, [["エンジョイ", "エンジョイ"], ["エンジョイandガチ", "エンジョイandガチ"], ["ガチ", "ガチ"]], include_blank: "選択してください" %>
        </div>
        <div class="age-field">
            <%= f.label :【平均年齢】 %><br />
            <%= f.select :average_age, [["１０代", "１０代"], ["２０代", "２０代"], ["３０代", "３０代"], ["４０代", "４０代"], ["５０代以上", "５０代以上"]], include_blank: "選択してください" %>
        </div>
        <div class="tag_list-field">
          <span class="badge badge-danger">必須</span><%= f.label :【ゲーム】 %><br />
          <%= f.collection_select:tag_list, @tags.all, :name, :name, include_blank: "選択してください" %>
        </div>

        <div class="actions">
          <% if  current_user.clans.count >= 3 %>
            <p class="btn btn_red col-sm-12"">クラン所属限度(3)</p>
          <% else %>
            <p><%= f.submit "クラン作成", class: "btn btn3 col-sm-12" %></p>
          <% end %>
        </div>
      <% end %>
      <p><%= link_to 'マイページへ戻る', current_user, class: "btn btn4 col-sm-12" %></p>
    </div>
  </div>
</div>

app/views/clans/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-sm-0 col-sm-12 offset-sm-0">
      <div class="guide-content">
        <div class="page_title text-center">
          <h5 style="font-size: x-large; font-weight: bold;">クラン: <%= @clan.name %></h5>
          <%= raw(@clan.tag_list.map { |t| link_to t, clans_path(tag_name: t), class: "profile-job" }.join(' ')) %>
        </div>
        <p class= "image_center">
          <% if @clan.image? %>
            <img src=<%= @clan.image %> class = "clan_image_show">
          <% else %>
            <%= image_tag 'default_clan.png', class: "clan_image_show" %>
          <% end %>
        </p>
      </div>




      <div class="container">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#tab1" role="tab" aria-controls="home" aria-expanded="true">クランTOP</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#tab2" role="tab" aria-controls="profile">メンバー(<%= @clan.users.count %>)</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#tab3" role="tab" aria-controls="profile">掲示板</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="1-tab"> 
            <%# クラン情報 %>
            <div class="tab-pane-header">
              <p class="user-index text-center" style="font-weight: bold; margin-bottom: 10px;">基本情報</p>
              <table style="width: 95%;">
                <tr><th>ステータス</th><td><%= @clan.status %></td></tr>
                <tr><th>レベル</th><td><%= @clan.level %></td></tr>
                <tr><th>雰囲気</th><td><%= @clan.atomosphere %></td></tr>
                <tr><th>平均年齢</th><td><%= @clan.average_age %></td></tr>
              </table>
              <section class="self-intro" style="width: 95%; margin: auto;">
                <div class="intro">
                  <% if @clan.clan_introduction %>
                    <%=safe_join(@clan.clan_introduction.split("\n"),tag(:br)) %>
                  <% else %>
                    <p>クラン紹介はまだありません。</p>
                  <% end %>
                </div>
              </section>
              
            
              <!-- コミュニティ参加・退会ボタン -->
              <% if user_signed_in? %>
                <div class="text-center">
                  <% if user_admin_flg(current_user, @clan) == 1 %>
                    <%= link_to "クラン編集", edit_clan_path, class:"btn btn2", data: {"turbolinks" => false} %>
                  <% end %>
                  <% if @clan.user_belonging?(current_user) %>
                      <%= link_to '退会する', clan_belonging_path(@clan, @belonging), method: :delete, data:{ confirm: "クラン「#{@clan.name}」を退会します。よろしいですか？" } ,class:"btn btn_mini_red" %>
                  <!-- 当該コミュニティには所属していないが、ログインはしている場合 -->
                  <% elsif current_user %>
                    <% if @request %>
                      <%= link_to '申請取消', clan_request_path(@clan, @request), method: :delete, data:{ confirm: "クラン「#{@clan.name}」への参加申請を取り消します。よろしいですか？" } ,class: "btn btn_mini_red" %>
                    <% elsif  current_user.clans.count >= 3%>
                      <p class="btn btn_mini_red">クラン所属限度(3)</p>
                    <% elsif  @clan.users.count >= 20%>
                      <p class="btn btn_mini_red">定員(20名)</p>
                    <% else %>
                      <%= link_to '参加申請', clan_requests_path(@clan), method: :post, class: "btn btn2" %>
                    <% end %>
                  <% end %>
                </div>
              <% else %>
                <p class="user-index text-center" style="font-weight: bold;">クランに参加するにはユーザー登録・ログインが必要です。</p>
                <div class="text-center">
                  <%= link_to "ユーザー登録", new_user_registration_path, class:"btn btn2" %>
                  <%= link_to "ログイン", new_user_session_path, class:"btn btn2" %>
                </div>
              <% end %>
            </div>


          </div>

          <%# メンバー %>
          <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="2-tab">
            <div class="tab-pane-header">   
              <!-- 所属メンバー一覧 START -->
              <p class="user-index text-center" style="font-weight: bold;">所属メンバ一リスト(定員:20名)</p>
              <div class="container">
                <div class="row">
                  <% @belongings.each do |belonging| %>
                    <%= link_to belonging.user do %>
                      <div class="profile-card">
                        <div class="profile-card__inner">
                          <div class="profile-thumb" style="boader: none; border-radius: 100px; border: #010ca3 3px solid;">
                            <% if belonging.user.image? %>
                              <img src=<%= belonging.user.image %> class = "clan_image">
                            <% else %>
                              <%= image_tag ("default-user-image.png"), class:"clan_image" %>
                            <% end %>
                          </div>
                          <div class="profile-content">
                          <span class="profile-name"><%= belonging.user.name %></span>
                          <span class="profile-job">
                            <% if belonging.admin_flg == 1 %>
                              <div class="admin"><i class="fas fa-crown"></i> クランマスター</div>
                            <% else %>
                              <span>&nbsp;</span>
                            <% end %>
                          </span>
                          <span class="profile-intro">
                            <table>
                              <tr><th>PSID</th><td><%= belonging.user.psid %></td></tr>
                              <tr><th>性別</th><td><%= belonging.user.sex %></td></tr>
                              <tr><th>年齢</th><td><%= belonging.user.age %></td></tr>
                              <tr><th>地域</th><td><%= belonging.user.address %></td></tr>
                            </table>
                          </span>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <!-- 承認待ちメンバーリスト START -->
              <% if user_admin_flg(current_user, @clan) == 1 %>
                <div class="container applicant-wrapper">
                  <p class="user-index text-center" style="font-weight: bold;">承認待ちユーザー</p>
                  <div class="row">
                    <% @clan.requests.each do |req| %>
                      <%= link_to req.user do %>
                        <div class="profile-card">
                          <div class="profile-card__inner">
                            <div class="profile-thumb" style="boader: none; border-radius: 100px; border: #010ca3 3px solid;">
                              <% if req.user.image? %>
                                <img src=<%= req.user.image %> class = "icon_image_mini">
                              <% else %>
                                <%= image_tag ("default-user-image.png"), class:"icon_image_mini" %>
                              <% end %>
                            </div>
                            <div class="profile-content">
                              <span class="profile-name"><%= req.user.name %></span>
                              <span class="profile-job">&nbsp;</span>
                              <span class="profile-intro">
                                <table>
                                  <tr><th>PSID</th><td><%= req.user.psid %></td></tr>
                                  <tr><th>性別</th><td><%= req.user.sex %></td></tr>
                                  <tr><th>年齢</th><td><%= req.user.age %></td></tr>
                                  <tr><th>地域</th><td><%= req.user.address %></td></tr>
                                </table>
                              </span>
                              <div class="text-center">
                                <%= link_to "承認", clan_belongings_path(req.clan, user_id: req.user.id, request_id: req.id), method: :post, class:"btn btn_req" %>
                                <%= link_to "却下", clan_request_path(req.clan, req), method: :delete, class:"btn btn_req2" %>
                              </div>
                            </div>  
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>

            </div>
          </div>


          <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="3-tab">

            <div class="tab-pane-header">

              <% if @clan.user_belonging?(current_user) %>
                <%# ボード一覧 %>
                <% @boards.each do |board| %>
                  <% if board.user == current_user %>
                    <div class="balloon_r" id="board-<%= board.id %>">
                      <div class="faceicon">
                        <% if board.user.image? %>
                          <img src=<%= board.user.image %>>
                        <% else %>
                          <%= image_tag ("default-user-image.png") %>
                        <% end %>
                      </div>
                      <div class="co-wrap">
                        <p class="says"><%= safe_join(board.content.split("\n"),tag(:br)) %></p>
                        <div style = "text-align: right;">
                          <%= board.created_at.strftime("%m月%d日 %H:%M") %>
                          <%= link_to '削除', clan_board_path(board_id: board.id, clan_id: @clan.id), method: :delete, remote: true, data: { confirm: '削除してよろしいですか？' }  %>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <div class="balloon_l">
                      <div class="co-wrap">
                        <div class="faceicon">
                          <% if board.user.image? %>
                            <img src=<%= board.user.image %>>
                          <% else %>
                            <%= image_tag ("default-user-image.png") %>
                          <% end %>
                        </div>
                        <p style="margin: 0 10px 0 10px; font-size: small;"><%= board.user.name %></p>
                      </div>
                      <div class="co-wrap">
                        <p class="says"><%= safe_join(board.content.split("\n"),tag(:br)) %></p>
                        <%= board.created_at.strftime("%m月%d日 %H:%M") %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
                <div class=boards>
                </div>

                
                <%# ボードフォーム %>
                <%= form_with(model: [@clan, @board], local: true, id: "new_board") do |form| %> 
                  <div class="form-group offset-sm-3 col-sm-6 offset-sm-3">
                    <%= form.text_area :content, :rows => "3", placeholder: "投稿内容を入力", autofocus: true, class: "form-control contentbox" %>
                  </div>
                  <div class="form_area__action" style="margin: 0px; padding: 0px; text-align: center;">
                    <%= form.submit "投稿", class: "btn btn2 form__submit" %>
                  </div>
                <% end %>
              <% else %>
                <p class="user-index text-center" style="font-weight: bold;">クラン所属メンバーのみ閲覧可</p>
              <% end %>

            </div>

          </div>
        </div>
      </div>  
    </div>
  </div>
</div>