config/routes.rb
Rails.application.routes.draw do
  # device
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, :only => [:show]
  root 'pages#home'
  get '/howto', to: 'pages#howto'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :clans do
    resources :requests, only: %i(create destroy)
    resources :belongings, only: %i(create destroy)
    resources :boards, only: [:index, :create, :update, :destroy]
  end
end

app/views/layouts/_error.html.erb
<% @clan.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_flushs.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar">
    <span class= "footer-license">©2020 Junkratmecha All Rights Reserved.</span>
    <div class="guide-link">
      <span class="text-right">
        <i class="fas fa-headphones-alt"><%=link_to " パーティープレイの始め方", howto_path, style: "color: #e9eef1; margin-right: 10px;" %></i>
        <i class="fas fa-question-circle"><%= link_to " 利用規約・お問い合わせ", terms_path, style: "color: #e9eef1; margin-right: 10px;" %></i>
        <i class="fas fa-book-reader"><%= link_to " プライバシーポリシー", privacy_path, style: "color: #e9eef1;" %></i>
      </span>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top header-nav shadow-sm">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo_white_1.png', style: "width: 100px;" %>
    <% end %>
    <button class="navbar-toggler" type="button"
        data-toggle="collapse"
        data-target="#responsiveMenu"
        aria-controls="responsiveMenu"
        aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="responsiveMenu">
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><i class="fas fa-handshake"></i><%= link_to ' クランを探す', clans_path %></li>
          <li class="nav-item"><i class="fas fa-flag"></i><%= link_to ' クランを作る', new_clan_path %></li>
          <li class="nav-item">
            <% if current_user.image? %>
              <img src=<%= current_user.image %> class = "icon_image_mini">
            <% else %>
              <%= image_tag 'default-user-image.png', class: "icon_image_mini" %>
            <% end %>
          </li>
          <li class="nav-item">
              <div class="dropdown"> 
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu dropdown-menu-right" style="color: #010ca3; text-align: left;">
                  <li class = "menu_item"><i class="fas fa-user-circle"></i><%= link_to ' マイページ', current_user %></li>
                  <li class = "menu_item"><i class="fas fa-cog"></i><%= link_to ' 設定', edit_user_registration_path , data: {"turbolinks" => false}%></li>
                  <li class = "menu_item"><i class="fas fa-sign-out-alt"></i><%= link_to ' ログアウト', destroy_user_session_path, method: :delete %></li>
                </ul>
              </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><i class="fas fa-handshake"></i><%= link_to ' クランを探す', clans_path %></li>
          <li class="nav-item"><i class="fas fa-user"></i><%= link_to ' ユーザー登録', new_user_registration_path %></li>
          <li class="nav-item"><i class="fas fa-sign-in-alt"></i><%= link_to ' ログイン', new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>-->
<!--  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">-->
<!--  </script>-->
<!--<![endif]-->-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9ea1484d19.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flushs' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>